# platform :ios, '8.0'

target 'TestGQWWithSwift' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks   use_frameworks!

  # Pods for TestGQWWithSwift
pod 'AFNetworking', '~> 3.1.0'
pod 'HexColors', '~> 4.0.0'
pod 'MJExtension', '~> 3.0.13'
pod 'IQKeyboardManager', '~> 3.3.7'
pod 'Masonry', '~> 1.0.0'
pod 'SDWebImage', '~> 3.8.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'iCarousel', '~> 1.8.3'
pod 'UMengAnalytics-NO-IDFA'
pod 'LCTabBarController'
end
